version: "3.8" #
services:
  db:
    image: postgres:16
    container_name: bigdata_snowflake_pg 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bigdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  
      - ./sql_scripts:/docker-entrypoint-initdb.d 
      - ./data:/csv_import_data                  

volumes: 
  pgdata: